### ISSUE TITLE
invalid syntax on match errCode: and match data:

### ISSUE THREAD

**Issue by jrunser** [flengyel/RYLR998-LoRa#1]
python 3.9.2. EN-UTF-8. SImply doesn't operate unmodified.

**Comment by jrunser** [comment]
Original poster (self) failed to use the required 3.10 python. Problem found between the screen and keyboard.

**Comment by flengyel** [comment]
This is my fault: I should have stated that the prerequisite is python 3.10+ instead of 3.9+. At some point I needed 3.10.
