### ISSUE TITLE
Problem Run App Python rylr998.py

### ISSUE THREAD

**Issue by niho06** [flengyel/RYLR998-LoRa#2]
Hello,

I have tried to use the code you developed but have not been successful.

It can only be run on Rasp4 or it is possible to run it on Windows PC using USB TTL. since I keep problem with the free RPi-GPIO.

it is not compatible with windows.

In the case of raspberry pi I have tried to make it run but without success. I installed everything necessary but when I try to run the putty application it crashes.

error in windows:
![image](https://github.com/flengyel/RYLR998-LoRa/assets/122945130/3f1fe3cc-acc0-4d68-9130-4fae71a08663)

error in raspberrypi 3B
![image](https://github.com/flengyel/RYLR998-LoRa/assets/122945130/a407d245-f061-4bfa-a944-f60a5b2a1c9f)

**Comment by flengyel** [comment]
I'll look at it, though I am swamped for the next few days. Looks like the initial import was indented.

**Comment by flengyel** [comment]
It runs on Windows 10 and 11 for me. Don't use GPIO under Windows. 
Use the --noGPIO flag to use a USB to TTL level shifter. What level shifter are you using?

**Comment by flengyel** [comment]
You have an unexpected indentation at line 66. The repository looks like this around line 66
existGPIO = True
try:
    import subprocess # for call to raspi-gpio
    import RPi.GPIO as GPIO
except RuntimeError:
    existGPIO = False

I'll try cloning the repository to a windows 11 machine and running it from there.

**Comment by flengyel** [comment]
I was running with WSL2 and Ubuntu 20.04 under Windows11. With Windows 11 directly, at least two modifications are necessary.  It appears that cur.set_escdelay(1) fails. Also, I have to allow ports of the form COM1...COM14...COM999. This is added. And the runtime error if RPi.GPIO is missing (which it will be on Windows) needs to be different.

**Comment by flengyel** [comment]
Windows needs the windows-curses library, but this lacks esc_delay(), which leads to erratic text handling under windows. I have added COM port support. You don't need RPi.GPIO under windows if you use a USB to TTL level shifter. You would have to comment out cur.set_escdelay(1) because this isn't handled with windows-curses, unless there is an alternative that handles it. The code might run under the RPi3, but I haven't tested it. There is a new version of the code.

**Comment by flengyel** [comment]
You're not supposed to run rylr998.py as sudo. I have never tested this and I do not recommend it. Do not load libraries as root.

**Comment by flengyel** [comment]
I'm closing this issue because your screenshots show that you are installing `asyncio` as root with `sudo pip install asyncio`. Start over with  `pip install asyncio`. I think you might want to upgrade `pip` too.

**Comment by niho06** [comment]
Very thankful,

the problem was the type of console I was using (putty).

After installing, I ran the application from CMD connected through port 22 to the raspberry and it worked.

thank you very much for your help

**Comment by flengyel** [comment]
@niho06 Thank you for opening this issue--it helped improve the code and documentation.
